services:
  app:
    image: "arvyy/scheme-index:${BRANCH}"
  nginx:
    image: "arvyy/scheme-index-nginx:${BRANCH}"
    volumes:
      - "../../docker/devcert/:/etc/letsencrypt/live/r7rsindex.com"
      - "../../docker/devcert/:/etc/letsencrypt/live/index.scheme.org"
  test:
    build:
      dockerfile: ./integrationtest/restassert/Dockerfile
      context: ../..
    depends_on:
      - nginx
      - app
