version: 2.1

jobs:
  unit-test:
    docker:
      - image: sbtscala/scala-sbt:eclipse-temurin-jammy-17.0.5_8_1.8.2_3.2.2
    steps:
      - checkout
      - run:
          name: Test
          command: |
            sbt test

  build-images:
    machine: true
    steps:
      - checkout
      - run: |
          docker build -t arvyy/scheme-index:$CIRCLE_BRANCH -f docker/scheme-index/Dockerfile .
          docker build -t arvyy/scheme-index-nginx:$CIRCLE_BRANCH -f docker/nginx/Dockerfile .
          mkdir -p /tmp/workspace/images
          docker save -o /tmp/workspace/images/scheme-index:$CIRCLE_BRANCH arvyy/scheme-index:$CIRCLE_BRANCH
          docker save -o /tmp/workspace/images/scheme-index-nginx:$CIRCLE_BRANCH arvyy/scheme-index-nginx:$CIRCLE_BRANCH
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - images

  integration-test:
    machine: true
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: |
          docker load -i /tmp/workspace/images/scheme-index:$CIRCLE_BRANCH
          docker load -i /tmp/workspace/images/scheme-index-nginx:$CIRCLE_BRANCH
          BRANCH=$CIRCLE_BRANCH docker compose up --abort-on-container-exit

  upload-images:
    machine: true
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: |
          docker load -i /tmp/workspace/images/scheme-index:$CIRCLE_BRANCH
          docker load -i /tmp/workspace/images/scheme-index-nginx:$CIRCLE_BRANCH
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          docker push arvyy/scheme-index:$CIRCLE_BRANCH
          docker push arvyy/scheme-index-nginx:$CIRCLE_BRANCH

  deploy:
    machine: true
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "bash ~/update.sh"

workflows:
  main:
    jobs:
      - unit-test
      - build-images
      - integration-test:
          requires:
            - build-images
      - upload-images:
          requires:
            - integration-test
      - deploy:
          requires:
            - upload-images
          filters:
            branches:
              only:
                - master
