services:
  app:
    image: "arvyy/scheme-index:master"
    volumes:
      - type: bind
        source: ./logs
        target: /app/logs

  nginx:
    image: "arvyy/scheme-index-nginx:master"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/letsencrypt/:/etc/letsencrypt/"
