services:
  base:
    image: scmindex-builder:latest
    build:
      dockerfile: ./docker/base/Dockerfile
      context: ..
  app:
    build:
      dockerfile: ./docker/scheme-index/Dockerfile
      context: ..
    depends_on:
      - base
    volumes:
      - type: bind
        source: ./logs
        target: /app/logs

  nginx:
    build:
      dockerfile: ./docker/nginx/Dockerfile
      context: ..
    depends_on:
      - base
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./devcert/:/etc/letsencrypt/live/r7rsindex.com"
      - "./devcert/:/etc/letsencrypt/live/index.scheme.org"
